version: '3.8'

services:
  # Airflow service
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow # Path to your Airflow Dockerfile
    ports:
      - "8080:8080" # Expose Airflow webserver port
    volumes:
      - ./airflow/dags:/opt/airflow/dags # Mount DAGs directory (if needed)
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false # Disable Airflow example DAGs

  # Flask application service
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask # Path to your Flask Dockerfile
    ports:
      - "5000:5000" # Expose Flask application port
    environment:
      - PORT=5000 # Set the port environment variable for Flask (if needed)
    depends_on:
      - mlflow_server # Ensure MLFlow server is started before Flask app

  # MLFlow server service
  mlflow_server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow # Path to your MLFlow Dockerfile
    ports:
      - "5001:5000" # Expose MLFlow server port
    environment:
      - MLFLOW_SERVER_HOST=0.0.0.0 # Set MLFlow server host to allow external access
